/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddNode: typeof import('./../components/bdWorkflow/nodes/addNode.vue')['default']
    Approver: typeof import('./../components/bdWorkflow/nodes/approver.vue')['default']
    BdAppVersion: typeof import('./../components/BdAppVersion/index.vue')['default']
    BdMsg: typeof import('./../components/BdMsg/index.vue')['default']
    BdPage: typeof import('./../components/BdPage/index.vue')['default']
    BdProhitWords: typeof import('./../components/BdProhitWords/index.vue')['default']
    BdSandAllMsg: typeof import('./../components/BdSandAllMsg/index.vue')['default']
    BdSendMsg: typeof import('./../components/BdSendMsg/index.vue')['default']
    BdStatistic: typeof import('./../components/BdStatistic/index.vue')['default']
    BdWorkflow: typeof import('./../components/bdWorkflow/index.vue')['default']
    Branch: typeof import('./../components/bdWorkflow/nodes/branch.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    NodeWrap: typeof import('./../components/bdWorkflow/nodeWrap.vue')['default']
    Promoter: typeof import('./../components/bdWorkflow/nodes/promoter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./../components/bdWorkflow/select.vue')['default']
    Send: typeof import('./../components/bdWorkflow/nodes/send.vue')['default']
    SwitchDark: typeof import('./../components/SwitchDark/index.vue')['default']
  }
}
