/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BdAppVersion: typeof import('./../components/BdAppVersion/index.vue')['default']
    BdMsg: typeof import('./../components/BdMsg/index.vue')['default']
    BdPage: typeof import('./../components/BdPage/index.vue')['default']
    BdProhitWords: typeof import('./../components/BdProhitWords/index.vue')['default']
    BdSandAllMsg: typeof import('./../components/BdSandAllMsg/index.vue')['default']
    BdSendMsg: typeof import('./../components/BdSendMsg/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwitchDark: typeof import('./../components/SwitchDark/index.vue')['default']
  }
}
